Repository ShadowLance2/Course_Work-Ethical-Keylogger-Stealer, pull requests merged in 2024-01, with the labels that each got.

#4 Работа над подзадачей №2
  Stealer_Keylogger.py
Labels: enhancement

#6 Подзадача №3
  Stealer_Keylogger.py
Labels: enhancement

#10 Выполнение подзадачи №5
  Mails_Extractor.py
Labels: Основная работа

#18 Работа над issue "Проектировщик №1"
  Проектировщик/Архитектура продукта.docx
Labels: documentation

#19 Работа над issue "Проектировщик №2"
  Проектировщик/Требования к системному ПО.docx
Labels: documentation

#20 Работа над задачей Руководитель №1
  Руководитель/Видение проекта.docx
Labels: documentation

#23 Работа над подзадачей №6
  Database_Inserter.py
Labels: Основная работа

#24 Работа над подзачей №7
  Database_Inserter.py
Labels: Основная работа

#25 Работа над issue Разработчик (№1)
  Разработчик/Языки программирования и обоснование.docx
Labels: documentation

#26 Работа над issue подзадача №4
  Stealer_Keylogger.py
Labels: enhancement

#28 Работа над issue Подзадача №9
  Administrator_Interface.py
Labels: Основная работа

#29 Работа над issue Подзадача №8
  Database_Inserter.py
  Mails_Extractor.py
  Mails_Extractor_Inserter.py
Labels: enhancement, Основная работа

#31 Работа над issue подзадача №10
  Administrator_Interface.py
  Administrator_Interface_Tools.py
Labels: enhancement, Основная работа

#34 Работа над issue подзадача №11
  Administrator_Interface_Tools.py
Labels: enhancement

#36 Работа над issue Подзадача №12
  Administrator_Interface_Tools.py
Labels: enhancement

#42 Работа над issue "Проектировщик (№4)"
  Проектировщик/Функциональная диаграмма (Диаграмма прецедентов - вариантов использования) UML.drawio
Labels: documentation

#43 Работа над issue "Проектировщик (№5)"
  Проектировщик/Диаграмма последовательности UML.drawio
Labels: documentation

#44 Работа над issue "Проектировщик (№6)"
  Проектировщик/Концептуальная модель БД.drawio
Labels: documentation

#46 Работа над "Разработчик №2"
  Разработчик/Диаграмма пакетов UML.drawio
Labels: documentation

#48 Работа над issue Разработчик №3
  Разработчик/Диаграмма физической модели БД.docx
Labels: documentation

#50 Работа над issue Руководитель №2
  Руководитель/Функциональная диаграмма продукта как он видится.drawio
Labels: documentation

#52 Поправки в архитектурную диаграмму
  Проектировщик/Архитектурная диаграмма.drawio
Labels: documentation

#54 Поправки в функциональных диаграммах, поправки в архитектурной диаграмме.
  Проектировщик/Архитектурная диаграмма.drawio
  Проектировщик/Функциональная диаграмма (Диаграмма прецедентов - вариантов использования) UML.drawio
  Проектировщик/Функциональные диаграммы (Диаграмма прецедентов, диаграмма состояний )UML.drawio
Labels: documentation

#56 Поправки в диаграмме деятельности.
  Проектировщик/Диаграмма последовательности UML.drawio
Labels: documentation

#66 Поправки в диаграмму прецедентов UML.
  Проектировщик/Функциональные диаграммы (Диаграмма прецедентов, диаграмма состояний )UML.drawio
Labels: documentation

#68 Готовая пояснительная записка к курсовой работе.
  Пояснительная записка РИ-311055 Коротков В.К; Чуфаров К.Н..docx
Labels: documentation, Основная работа

#70 Поправки в пояснительной записке
  Пояснительная записка РИ-311055 Коротков В.К; Чуфаров К.Н..docx
Labels: documentation, Основная работа
